"""Validate the public NYC coydog pedigree against dog and coyote references.

This is deliberately a small, laptop-safe, cross-study reanalysis.  It uses the
267 WGS/RADseq bridge loci already prepared in ``data/eastern_coyote_wgs_bridge``
and calls those same loci from the aligned RADseq records for the four key NYC
animals: the reported F1 (NY01), its two reported coyote backcross offspring
(NY04 and NY05), and their coyote mother (T211).

The output is a validation of the published pedigree signal, not a new
whole-genome ancestry estimate.  In particular, the reference WGS and NYC
RADseq data were generated by different studies and platforms.
"""

from __future__ import annotations

import argparse
import csv
import gzip
import json
import math
import re
import subprocess
import sys
from collections import Counter, defaultdict
from datetime import UTC, datetime
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
import prepare_redwolf_jackal_aadr as indexed_vcf

WGS_SAMPLES = (
    "Coyote01",
    "Coyote02",
    "Coyote03",
    "Beagle01",
    "Beagle02",
    "Chihuahua01",
    "Chihuahua03",
    "GermanShepherd01",
    "GermanShepherd02",
    "GoldenRetriever01",
    "GoldenRetriever02",
    "LabradorRetriever01",
    "LabradorRetriever02",
)
COYOTE_SAMPLES = frozenset(WGS_SAMPLES[:3])
NYC_RUNS = {
    "T211": "SRR20089555",
    "NY05": "SRR20089559",
    "NY04": "SRR20089560",
    "NY01": "SRR20089561",
}
# Conservative total from the SRA RunInfo ``size_MB`` values (149 MB combined).
NYC_SRA_BYTES_UPPER_BOUND = 149_000_000
CIGAR = re.compile(r"(\d+)([MIDNSHP=X])")


def bridge_sites(path: Path) -> dict[tuple[str, int], tuple[str, str]]:
    sites: dict[tuple[str, int], tuple[str, str]] = {}
    with gzip.open(path, "rt", encoding="utf-8") as handle:
        for line in handle:
            if not line or line.startswith("#"):
                continue
            fields = line.rstrip().split("\t")
            if len(fields) < 5:
                continue
            sites[(fields[0], int(fields[1]))] = (fields[3].upper(), fields[4].upper())
    if len(sites) < 100:
        raise RuntimeError(f"bridge panel is unexpectedly small ({len(sites)} loci)")
    return sites


def load_wgs_reference(
    sites: dict[tuple[str, int], tuple[str, str]], out_dir: Path, max_bytes: int
) -> tuple[dict[tuple[str, int], list[str]], dict[str, object]]:
    """Extract selected WGS samples at bridge coordinates using tabix byte ranges."""
    index_path = out_dir / "722g.990.SNP.INDEL.chrAll.vcf.gz.tbi"
    budget = indexed_vcf.TransferBudget(max_bytes)
    if index_path.exists():
        raw_index = index_path.read_bytes()
    else:
        raw_index = indexed_vcf._request(f"{indexed_vcf.SOURCE_VCF_URL}.tbi", budget)
        index_path.write_bytes(raw_index)
    names, indexes = indexed_vcf._parse_tabix(raw_index)
    by_chrom = dict(zip(names, indexes, strict=True))
    missing_chromosomes = sorted({chrom for chrom, _ in sites if chrom not in by_chrom})
    if missing_chromosomes:
        raise RuntimeError(f"bridge chromosomes absent from WGS index: {missing_chromosomes}")

    chunks: set[tuple[int, int]] = set()
    for chrom, pos in sites:
        chunks.update(indexed_vcf._chunks_for(by_chrom[chrom], pos))
    merged = indexed_vcf._merge_chunks(chunks)
    estimated_wgs = sum(
        ((end >> 16) + indexed_vcf.BGZF_MAX_BLOCK) - (begin >> 16) for begin, end in merged
    )
    if budget.used + estimated_wgs + NYC_SRA_BYTES_UPPER_BOUND > max_bytes:
        raise RuntimeError(
            "conservative transfer preflight exceeds safety limit: "
            f"{budget.used + estimated_wgs + NYC_SRA_BYTES_UPPER_BOUND:,} > {max_bytes:,} bytes"
        )

    _, columns = indexed_vcf._source_header(indexed_vcf.SOURCE_VCF_URL, budget)
    missing_samples = [sample for sample in WGS_SAMPLES if sample not in columns]
    if missing_samples:
        raise RuntimeError(f"WGS reference samples absent from source VCF: {missing_samples}")
    sample_columns = [columns.index(sample) for sample in WGS_SAMPLES]
    reference: dict[tuple[str, int], list[str]] = {}
    for ordinal, (virtual_begin, virtual_end) in enumerate(merged, start=1):
        start = virtual_begin >> 16
        end = (virtual_end >> 16) + indexed_vcf.BGZF_MAX_BLOCK - 1
        raw = indexed_vcf._request(indexed_vcf.SOURCE_VCF_URL, budget, (start, end))
        text = indexed_vcf._decompress_bgzf(raw, virtual_begin & 0xFFFF).decode(errors="replace")
        for line in text.splitlines():
            if not line or line.startswith("#"):
                continue
            fields = line.split("\t")
            if len(fields) <= max(sample_columns):
                continue
            try:
                key = (fields[0], int(fields[1]))
            except (IndexError, ValueError):
                continue
            if key not in sites or key in reference:
                continue
            ref, alt = sites[key]
            if fields[3].upper() != ref or fields[4].upper() != alt:
                continue
            format_fields = fields[8].split(":")
            if "GT" not in format_fields:
                continue
            gt_index = format_fields.index("GT")
            calls = [indexed_vcf._genotype(fields[index], gt_index) for index in sample_columns]
            if all(call is not None for call in calls):
                reference[key] = [str(call) for call in calls]
        if ordinal % 50 == 0 or ordinal == len(merged):
            print(
                f"WGS ranges {ordinal}/{len(merged)}; retained {len(reference)} bridge sites",
                flush=True,
            )
    metadata = {
        "n_ranges": len(merged),
        "estimated_wgs_bytes": estimated_wgs,
        "downloaded_wgs_bytes": budget.used,
        "retained_reference_sites": len(reference),
    }
    return reference, metadata


def sra_chromosome(chrom: str) -> str:
    number = int(chrom.removeprefix("chr"))
    return f"chr{number:02d}"


def base_at_site(fields: list[str], target: int) -> tuple[str, int] | None:
    """Return an aligned base and Phred score at ``target`` for one SAM record."""
    flag, start, mapq, cigar, sequence, quality = (
        int(fields[1]),
        int(fields[3]),
        int(fields[4]),
        fields[5],
        fields[9],
        fields[10],
    )
    if flag & 0xD04 or mapq < 30 or cigar == "*" or sequence == "*":
        return None
    reference_position = start
    query_position = 0
    for match in CIGAR.finditer(cigar):
        length, operation = int(match.group(1)), match.group(2)
        if operation in "M=X":
            if reference_position <= target < reference_position + length:
                index = query_position + target - reference_position
                if index >= len(sequence) or index >= len(quality):
                    return None
                return sequence[index].upper(), ord(quality[index]) - 33
            reference_position += length
            query_position += length
        elif operation in "IS":
            query_position += length
        elif operation in "DN":
            reference_position += length
        # H and P consume neither sequence nor reference.
    return None


def call_nyc_sample(
    sam_dump: Path, run: str, sites: dict[tuple[str, int], tuple[str, str]], min_depth: int
) -> dict[tuple[str, int], tuple[str | None, int, int, int]]:
    """Call bridge sites from archived coordinate-sorted RADseq alignments."""
    regions: list[str] = []
    for chrom, pos in sorted(sites, key=lambda item: (int(item[0].removeprefix("chr")), item[1])):
        regions.extend(
            ["--aligned-region", f"{sra_chromosome(chrom)}:{max(1, pos - 160)}-{pos + 160}"]
        )
    result = subprocess.run(
        [str(sam_dump), *regions, run], text=True, capture_output=True, check=True
    )
    counts: dict[tuple[str, int], Counter[str]] = defaultdict(Counter)
    for line in result.stdout.splitlines():
        if not line or line.startswith("@"):
            continue
        fields = line.split("\t")
        if len(fields) < 11:
            continue
        chrom = f"chr{int(fields[2].removeprefix('chr'))}"
        try:
            read_start = int(fields[3])
        except ValueError:
            continue
        # At most a few bridge windows overlap a RAD read; test only those windows.
        for key in sites:
            if key[0] != chrom or not read_start - 200 <= key[1] <= read_start + 350:
                continue
            observation = base_at_site(fields, key[1])
            if observation is None:
                continue
            base, phred = observation
            if phred >= 20:
                counts[key][base] += 1

    calls: dict[tuple[str, int], tuple[str | None, int, int, int]] = {}
    for key, (ref, alt) in sites.items():
        ref_count, alt_count = counts[key][ref], counts[key][alt]
        depth = ref_count + alt_count
        if depth < min_depth:
            calls[key] = (None, depth, ref_count, alt_count)
            continue
        fraction = alt_count / depth
        call = "0/0" if fraction <= 0.15 else "1/1" if fraction >= 0.85 else "0/1"
        calls[key] = (call, depth, ref_count, alt_count)
    return calls


def recalculate_calls_from_csv(
    path: Path, sites: dict[tuple[str, int], tuple[str, str]], min_depth: int
) -> dict[tuple[str, int], tuple[str | None, int, int, int]]:
    """Reapply a depth threshold to already-extracted per-site allele counts."""
    calls: dict[tuple[str, int], tuple[str | None, int, int, int]] = {}
    with path.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            key = (row["chrom"], int(row["position"]))
            if key not in sites:
                continue
            depth, ref_count, alt_count = (
                int(row[name]) for name in ("depth", "ref_count", "alt_count")
            )
            if depth < min_depth:
                calls[key] = (None, depth, ref_count, alt_count)
                continue
            fraction = alt_count / depth
            call = "0/0" if fraction <= 0.15 else "1/1" if fraction >= 0.85 else "0/1"
            calls[key] = (call, depth, ref_count, alt_count)
    if set(calls) != set(sites):
        raise RuntimeError(f"saved calls do not cover the requested reference sites: {path}")
    return calls


def dosage(gt: str) -> float:
    return sum(int(allele) for allele in gt.replace("|", "/").split("/")) / 2.0


def infer_dog_fraction(
    calls: dict[tuple[str, int], tuple[str | None, int, int, int]],
    reference: dict[tuple[str, int], list[str]],
) -> tuple[float | None, int, float | None]:
    numerator = denominator = 0.0
    called = 0
    for key, genotypes in reference.items():
        coyote = np.mean(
            [
                dosage(gt)
                for gt, sample in zip(genotypes, WGS_SAMPLES, strict=True)
                if sample in COYOTE_SAMPLES
            ]
        )
        dog = np.mean(
            [
                dosage(gt)
                for gt, sample in zip(genotypes, WGS_SAMPLES, strict=True)
                if sample not in COYOTE_SAMPLES
            ]
        )
        difference = dog - coyote
        observed = calls[key][0]
        if observed is None or abs(difference) < 0.40:
            continue
        called += 1
        numerator += (dosage(observed) - coyote) * difference
        denominator += difference * difference
    if called < 20 or denominator == 0:
        return None, called, None
    estimate = max(0.0, min(1.0, numerator / denominator))
    # Per-locus residual RMSE is a useful stability diagnostic for this small panel.
    residuals = []
    for key, genotypes in reference.items():
        observed = calls[key][0]
        if observed is None:
            continue
        coyote = np.mean(
            [
                dosage(gt)
                for gt, sample in zip(genotypes, WGS_SAMPLES, strict=True)
                if sample in COYOTE_SAMPLES
            ]
        )
        dog = np.mean(
            [
                dosage(gt)
                for gt, sample in zip(genotypes, WGS_SAMPLES, strict=True)
                if sample not in COYOTE_SAMPLES
            ]
        )
        if abs(dog - coyote) >= 0.40:
            residuals.append((dosage(observed) - (coyote + estimate * (dog - coyote))) ** 2)
    return estimate, called, math.sqrt(float(np.mean(residuals))) if residuals else None


def validate(rows: list[dict[str, object]]) -> dict[str, object]:
    by_id = {str(row["sample_id"]): row for row in rows}
    ny01 = by_id["NY01"]["dog_fraction"]
    t211 = by_id["T211"]["dog_fraction"]
    offspring = [by_id[name]["dog_fraction"] for name in ("NY04", "NY05")]
    available = all(value is not None for value in [ny01, t211, *offspring])
    passed = bool(
        available
        and abs(float(ny01) - 0.46) <= 0.20
        and float(t211) <= 0.20
        and all(0.08 <= float(value) <= 0.45 for value in offspring)
        and all(float(value) < float(ny01) for value in offspring)
    )
    return {
        "passed": passed,
        "criterion": (
            "at least 20 diagnostic calls per sample; NY01 near the published 46% dog ancestry "
            "(within 0.20), T211 <= 0.20, and both offspring between 0.08 and 0.45 and below NY01"
        ),
        "interpretation": (
            "Pass supports the expected F1 coyote-dog plus coyote-backcross pattern on this "
            "independent cross-platform bridge panel. It is not a replacement for a full "
            "local-ancestry analysis."
        ),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--bridge-vcf",
        type=Path,
        default=Path("data/eastern_coyote_wgs_bridge/eastern_coyote_wgs_bridge_1000.vcf.gz"),
    )
    parser.add_argument("--out-dir", type=Path, default=Path("data/nyc_coydog_validation"))
    parser.add_argument(
        "--sam-dump", type=Path, default=Path("data/tools/sratoolkit.3.4.1-win64/bin/sam-dump.exe")
    )
    parser.add_argument(
        "--reference-json",
        type=Path,
        help="reuse a previously extracted WGS reference_genotypes.json",
    )
    parser.add_argument(
        "--reuse-call-dir",
        type=Path,
        help="recalculate from saved per-sample calls instead of rereading SRA",
    )
    parser.add_argument(
        "--min-depth",
        type=int,
        default=8,
        help="minimum REF+ALT depth for a RADseq genotype call (default: 8)",
    )
    parser.add_argument("--max-download-bytes", type=int, default=9_000_000_000)
    args = parser.parse_args()
    if not args.sam_dump.exists():
        parser.error(f"sam-dump not found: {args.sam_dump}")
    if not args.bridge_vcf.exists():
        parser.error(f"bridge VCF not found: {args.bridge_vcf}")
    if not 1 <= args.max_download_bytes < 10_000_000_000:
        parser.error("--max-download-bytes must be positive and below 10 GB")
    if args.min_depth < 4:
        parser.error("--min-depth must be at least 4")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    sites = bridge_sites(args.bridge_vcf)
    print(f"Using {len(sites)} shared WGS/RADseq bridge loci", flush=True)
    if args.reference_json:
        saved = json.loads(args.reference_json.read_text(encoding="utf-8"))
        reference = {
            (key.rsplit(":", 1)[0], int(key.rsplit(":", 1)[1])): values
            for key, values in saved.items()
        }
        wgs_metadata: dict[str, object] = {
            "reused_reference_genotypes": str(args.reference_json),
            "retained_reference_sites": len(reference),
        }
    else:
        reference, wgs_metadata = load_wgs_reference(sites, args.out_dir, args.max_download_bytes)
    if len(reference) < 100:
        raise RuntimeError(f"only {len(reference)} reference loci retained")
    (args.out_dir / "reference_genotypes.json").write_text(
        json.dumps(
            {f"{chrom}:{pos}": values for (chrom, pos), values in reference.items()}, indent=2
        )
        + "\n",
        encoding="utf-8",
    )

    rows: list[dict[str, object]] = []
    for sample_id, run in NYC_RUNS.items():
        selected_sites = {key: sites[key] for key in reference}
        if args.reuse_call_dir:
            print(f"Recalculating {sample_id} from saved allele counts", flush=True)
            calls = recalculate_calls_from_csv(
                args.reuse_call_dir / f"{sample_id}_calls.csv", selected_sites, args.min_depth
            )
        else:
            print(f"Calling {sample_id} from {run}", flush=True)
            calls = call_nyc_sample(args.sam_dump, run, selected_sites, args.min_depth)
        dog_fraction, diagnostic_calls, rmse = infer_dog_fraction(calls, reference)
        rows.append(
            {
                "sample_id": sample_id,
                "run": run,
                "dog_fraction": dog_fraction,
                "diagnostic_sites_called": diagnostic_calls,
                "mean_depth": round(
                    float(np.mean([depth for _, depth, _, _ in calls.values()])), 2
                ),
                "residual_rmse": rmse,
            }
        )
        with (args.out_dir / f"{sample_id}_calls.csv").open(
            "w", newline="", encoding="utf-8"
        ) as handle:
            writer = csv.writer(handle)
            writer.writerow(
                ["chrom", "position", "ref", "alt", "gt", "depth", "ref_count", "alt_count"]
            )
            for (chrom, pos), (gt, depth, ref_count, alt_count) in sorted(calls.items()):
                ref, alt = sites[(chrom, pos)]
                writer.writerow([chrom, pos, ref, alt, gt or "./.", depth, ref_count, alt_count])

    with (args.out_dir / "ancestry_validation.csv").open(
        "w", newline="", encoding="utf-8"
    ) as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    verdict = validate(rows)
    manifest = {
        "created_utc": datetime.now(UTC).isoformat(timespec="seconds"),
        "sources": {
            "nyc_radseq_bioproject": "PRJNA857904",
            "nyc_runs": NYC_RUNS,
            "wgs_bioproject": "PRJNA448733",
            "wgs_reference_samples": list(WGS_SAMPLES),
            "bridge_vcf": str(args.bridge_vcf),
        },
        "transfer": {
            **wgs_metadata,
            "conservative_nyc_sra_bytes_upper_bound": NYC_SRA_BYTES_UPPER_BOUND,
            "hard_limit_bytes": args.max_download_bytes,
        },
        "calling": {
            "minimum_depth": args.min_depth,
            "minimum_base_quality": 20,
            "minimum_mapping_quality": 30,
            "reused_saved_counts_from": str(args.reuse_call_dir) if args.reuse_call_dir else None,
        },
        "results": rows,
        "validation": verdict,
        "limitations": [
            "267 cross-platform bridge loci rather than a jointly called whole genome.",
            "Dog ancestry is relative to a broad 10-dog reference set, not a local NYC dog panel.",
            "Use as a reproducible phenotype/pedigree check, not a legal, veterinary, "
            "or management diagnosis.",
        ],
    }
    (args.out_dir / "validation.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )
    print(
        json.dumps({"validation_passed": verdict["passed"], "results": rows}, indent=2), flush=True
    )


if __name__ == "__main__":
    main()
